### ISSUE TITLE
VOXCONVERT: Supporting Multiple --output Parameters

### ISSUE THREAD

**Issue by hkunz** [vengi-voxel/vengi#391]
It would greatly enhance versatility if we could specify multiple `--output` parameters. This would allow for converting input files into multiple formats simultaneously, such as `--output out.obj --output out.vox`. However, it's crucial to consider the potential impact on processing time. If executing multiple conversions within a single command significantly increases efficiency, this feature would be immensely beneficial. Otherwise, it might be more practical to execute separate voxconvert commands for each output type. As such, the efficiency gained from consolidating conversions would be a key factor in determining the usefulness of this feature, particularly in scenarios like mine.

**Comment by mgerhardy** [comment]
Thanks a lot for the suggestion - implemented with the linked commit. Let me know if anything isn't working as expected.

**Comment by hkunz** [comment]
thank you so much for implementing this feature!
