### ISSUE TITLE
BUILD: mac version of all modules missing in build deployment

### ISSUE THREAD

**Issue by hkunz** [vengi-voxel/vengi#431]
The mac versions of all modules are missing in recent builds. Issue since 0.0.29. I've looked through the issues and couldn't find anything related to this so I created this ticket. The links for the mac versions are empty despite it saying the upload being successful

Example link not working even though it says it was successfully uploaded:
```
Artifact mac-dmg has been successfully uploaded! Final size is ***752267 bytes. Artifact ID is ***356556544
Artifact download URL: https://github.com/vengi-voxel/vengi/actions/runs/842379***337/artifacts/***356556544
```

![err404](https://github.com/vengi-voxel/vengi/assets/2459196/84e55753-60dd-45e4-8ef7-6c3a52784bf6)

Also evident in the [tag urls](https://github.com/vengi-voxel/vengi/releases/tag/v0.0.30) that the files are missing:

![IMG_20240327_042336](https://github.com/vengi-voxel/vengi/assets/2459196/dc404c88-6421-40de-b0ba-6cff0f73ccc4)

**Comment by mgerhardy** [comment]
Not sure about this one - they are attached to each pipeline run - e.g. see here https://github.com/vengi-voxel/vengi/actions/runs/8423791337

**Comment by hkunz** [comment]
Oh I only checked the the tags here https://github.com/vengi-voxel/vengi/tags where I noticed the mac versions were missing. Any ideas? 
![IMG_20240327_042336](https://github.com/vengi-voxel/vengi/assets/2459196/dc404c88-6421-40de-b0ba-6cff0f73ccc4)

**Comment by hkunz** [comment]
I see it says successful but then the links are empty for the mac versions like:

```
Artifact mac-dmg has been successfully uploaded! Final size is ***752267 bytes. Artifact ID is ***356556544
Artifact download URL: https://github.com/vengi-voxel/vengi/actions/runs/842379***337/artifacts/***356556544
```

**Comment by mgerhardy** [comment]
attached the dmg to v0.0.30 - please double check - if it doesn't work, just re-open the ticket
