### ISSUE TITLE
VOXCONVERT: --surface-only produces internal faces

### ISSUE THREAD

**Issue by mgerhardy** [vengi-voxel/vengi#432]
> When I voxconvert a `.vox` file with only surface voxels to `.obj` using `--surface-only` it produces internal faces.
> I am sure it's a closed object (no holes)

[untitled.vox.zip](https://github.com/vengi-voxel/vengi/files/14761359/untitled.vox.zip)

This is most likely a problem with the cubic mesh extractor code - as it should only ever generate external visible faces.

`--surface-only` just calls `voxelutil::visitUndergroundVolume` to erase all non-visible voxels - should not have any impact on the result

FYI @hkunz

**Comment by hkunz** [comment]
Yes all non visible voxels did not impact the result. The internal faces are actually remnants of the visible surface-only voxels. It's like the visible surface voxels were just converted to mesh boxes so the back/invisible faces of those surface voxels were not removed.

**Comment by mgerhardy** [comment]
See the attached commit and the clarification of the docs - this is intended behavior. You should fill the hollows before. There are examples in the docs on how to do that.
