### ISSUE TITLE
Feature Request: Option for Rounded Voxels or Smooth Border Effects

### ISSUE THREAD

**Issue by imvenx** [vengi-voxel/vengi#451]
Hello MagicaVoxel Team,

I am an enthusiastic user of MagicaVoxel and appreciate the continuous efforts to improve this wonderful tool. I wanted to propose a feature that might add a new dimension of creativity for artists using this software.

**Feature Description:**

I suggest introducing a feature that allows for rounded voxel effects, particularly at the borders. This would not necessarily alter the fundamental cubic nature of voxels but could be implemented as a visual smoothing effect. Such an option would enable artists to create models with smoother transitions and rounded edges, enhancing the aesthetic possibilities without compromising the voxel art integrity.

Other option which I favour more altho may be more complex could be to add rounded buiding blocks:

Edge Voxels: These would have two adjacent faces rounded, functioning as a bridge between two standard voxel faces. This would soften the transition between the two connecting surfaces, useful for creating smoother outlines along edges.

Corner Voxels: These would involve three connected faces being rounded. This type of voxel would be particularly useful at the vertices where three voxel faces meet, allowing for a more spherical corner rather than a sharp point.

Probably there are more options to consider.

**Potential Benefits:**

- Increased stylistic flexibility
- Enhanced visual appeal for models requiring smoother outlines
- Broadened user base attracted by the ability to create more varied designs

I understand this might pose technical challenges, considering the inherent square nature of voxels, but even a feature that simulates rounded edges or smoother transitions would be greatly beneficial.

**Comment by mgerhardy** [comment]
Hello,

I'm sorry, this is not magicavoxel - but vengi ;)

If you are going to propose this for magicavoxel, you should most likely do this via twitter (the only communication channel I know for magicavoxel)

I think what you propose here might already exist in vengi as marching cube meshing.
See https://vengi-voxel.github.io/vengi/Configuration/#voxel-settings `voxel_meshmode` description

**Comment by imvenx** [comment]
lol, sorry! haha, I just typed magicaVoxel on duckduckgo and bring me here and I thought it was the same. I'm going to take a look to this then! Thank you!
