### ISSUE TITLE
VOXEDIT: Palette switching and color match to palette file unsupported

### ISSUE THREAD

**Issue by Mortecha** [vengi-voxel/vengi#495]
I've found that Loading a palette works but changes the Voxel colors as expected, however when I try to switch to a palette either with or without color matching enabled, I receive notifications stating that the palette file is unsupported. Even though it loads correctly.

I've also tried this with an exported built-in palette to the same effect.  

![2024-07-29 14_54_33-Settings](https://github.com/user-attachments/assets/383572e2-61d0-4bb7-9b94-5ca367c3b385)

I've looked in the app data folder and tried to open the copied palette image, I'm greeted with this message. The image file size is also 0kb. 

![2024-07-29 15_03_36-IrfanView](https://github.com/user-attachments/assets/b505a2d6-f864-47b8-ac2b-5869f0dd1c87)
![2024-07-29 15_05_00-Window](https://github.com/user-attachments/assets/205b3672-aed0-4cfb-9ca8-c15ce41a7629)

Manually copying the palette over to AppData and replacing the faulty 0kb palette file fixes this issue

**Comment by mgerhardy** [comment]
How did you copy the palette? From within `vengi-voxedit` I suppose - but with a load? With an export? Via console command? I currently can't reproduce this but found a code path that is not using the full filename (it omits the file extension - and that is suspicious)

**Comment by Mortecha** [comment]
How did copy it into AppData? I copy pasted a file palette with the same name and replaced the file when prompted by Windows. 

To start with, and how this problem emerged. I loaded in a custom palette, its a 256x1 exactly like an exported palette. I had to then undo the palette change to the voxel to retail it's original colors, loading in a palette also changes the current palette and messes up the current voxel colors. I then switched palettes to the one I had just loaded and the error emerged. 

I then exported an inbuilt palette and did the same thing to test, that produced the same error which I had found odd.

**Comment by Mortecha** [comment]
Looking forward to testing this on the next release, thanks for the swift work on this bug and also thank you for dedicating alot of time and resources to developing this tool!

**Comment by mgerhardy** [comment]
There are always builds attached to each pipeline run. e.g. here: https://github.com/vengi-voxel/vengi/actions/runs/10149845828

Just scroll down and download the win-voxedit  artifact if you feel like validating the fix. And thanks a lot for the report.

**Comment by mgerhardy** [comment]
I could reproduce this issue - and the attached commit fixes the issue for me. If not for you, please re-open. Thanks a lot for the report - much appreciated
