### ISSUE TITLE
VOXEDIT: File browser side pane is not consistent with Windows explorer layout

### ISSUE THREAD

**Issue by Metadorius** [vengi-voxel/vengi#515]
Currently when opening something in Vengi the left sidebar looks like this:

![image](https://github.com/user-attachments/assets/5c4af0f5-ab07-4545-a417-8a1094daa441)

It is actually inconsistent with how Windows Explorer draws this pane, the drives should be the only thing that is displayed in the This PC tab, and they shouldn't be in Quick Access. Additionally you can pin stuff to Quick Access and it also lists recently opened folders, so it's both recent folders and bookmarks kinda:

![image](https://github.com/user-attachments/assets/38fbef84-79af-4176-a7ff-42f627987120)

**Comment by mgerhardy** [comment]
![Bildschirmfoto vom 2024-09-15 14-14-18](https://github.com/user-attachments/assets/3851684f-c59e-4bbd-acad-af0f51c2aa5a)

this is what it is looking on linux now. If you could validate the current state on windows and think this is fixed for you, please let me know or close the ticket. Thanks a lot for the report
