### ISSUE TITLE
VOXEDIT: File sorting should be alphanumeric

### ISSUE THREAD

**Issue by Metadorius** [vengi-voxel/vengi#516]
![image](https://github.com/user-attachments/assets/b6a58b3d-a835-4dd3-9487-8b1d99a577f4)
Currently Vengi does seem to sort plainly by character code. This will yield issues like capitalized folders being sorted first and uncapitalized, IIRC none of the file explorers do this on neither of the OSes. Also this will result in numbers appearing like `1, 10, 11, ..., 2, 20, 21, ...` instead of `1, 2, ..., 10, 11, ..., 20, 21, ...`

**Comment by mgerhardy** [comment]
![Bildschirmfoto vom 2024-09-15 14-43-14](https://github.com/user-attachments/assets/ccfb5168-1567-4e6f-bde2-602c86dd09b0)

should be fixed now
