### ISSUE TITLE
VOXEDIT: File browser dialog doesn't accept letters being typed as a quick search

### ISSUE THREAD

**Issue by Metadorius** [vengi-voxel/vengi#517]
When the file/folder list is focused, when you start typing a folder name, like `vxl`, it will focus the first file/folder that starts with this name, or if no such name exists - the next letter that you type will produce a warning sound. In this case it should focus this folder:
![image](https://github.com/user-attachments/assets/24a5a90b-e5ec-442e-9507-713a4e2b680a)

**Comment by mgerhardy** [comment]
Jumping works for the first letter of the name right now
